control_visit_seven3x/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('relatorio/', views.relatorio, name='relatorio'),
    path('contatos/', views.contatos, name='contatos'),
    path('accounts/', include('django.contrib.auth.urls'))

    
]
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class visitante(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    data = models.DateTimeField(auto_now=True)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    celular = models.CharField(max_length=100)
    fone = models.CharField(max_length=100)
    #endereço
    cep = models.CharField(max_length=20)
    endereco = models.CharField(max_length=150)
    complemento = models.CharField(max_length=100)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class visita(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    data = models.DateTimeField(auto_now=True)
    visitante = models.ForeignKey(visitante, on_delete=models.PROTECT)
    descricao = models.TextField(max_length=5000)

    def __str__(self):
        return self.descricao

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import visitante, visita
from datetime import date
from django.shortcuts import render


def home(requests):
    return render(requests, 'core/home.html')

#página form cadastro visita
@login_required
def cadastro(request):
    #BUSCAR VISITANTES PARA MODAL
    visitantes = visitante.objects.all()
    horas = date.today()
    atualizando = ""

    if request.method == 'POST': # se clicar em salvar, faz
        refresh = False
        print("refresh false 01")
        for item in visitantes:
            print("FOR ITEM INICIO")
            if item.nome == request.POST.get("name") and item.cidade == request.POST.get("city"):
                refresh = True
                print("refresh true 02")
                item.nome = request.POST.get("name")
                item.email = request.POST.get("mail")
                item.celular = request.POST.get("cel")
                item.fone = request.POST.get("fone")
                item.cep = request.POST.get("zip")
                item.endereco = request.POST.get("address")
                item.complemento = request.POST.get("complement")
                item.cidade = request.POST.get("city")
                item.estado = request.POST.get("state")
                item.save()
                
                cadastrarvisita = visita.objects.create(
                    usuario = request.user,
                    visitante = item,
                    descricao = request.POST.get("description"),
                )
                return render(request, 'core/cadastro.html', {"horas":horas, "visitantes":visitantes, "atualizando":atualizando})
                
        if refresh == False:
            print("IF refresh false 03")
            nome = request.POST.get("name")
            email = request.POST.get("mail")
            celular = request.POST.get("cel")
            fone = request.POST.get("fone")
            cep = request.POST.get("zip")
            endereco = request.POST.get("address")
            complemento = request.POST.get("complement")
            cidade = request.POST.get("city")
            estado = request.POST.get("state")
            descricao = request.POST.get("description")
            cadastrarvisitante = visitante.objects.create(
                usuario = request.user,
                nome = nome,
                email = email,
                celular = celular,
                fone = fone,
                cep = cep,
                endereco = endereco,
                complemento = complemento,
                cidade = cidade,
                estado = estado)
            
            cadastrarvisita = visita.objects.create(
                usuario = request.user,
                visitante = cadastrarvisitante,
                descricao = descricao,
            )
            visitantes = visitante.objects.all()
            return render(request, 'core/cadastro.html', {"horas":horas, "visitantes":visitantes, "atualizando":atualizando, "nome_pagina":"Cadastro de nova visita"})

    #SE BUSCAR VISITANTE NO MODAL
    busca = request.GET.get('search')
    if busca:
        print("IF BUSCAR 04")
        atualizando = visitante.objects.get(id = busca)
    print("ULTIMO RETURN")
    return render(request, 'core/cadastro.html', {"horas":horas, "visitantes":visitantes, "atualizando":atualizando,  "nome_pagina":"Cadastro de nova visita"})


@login_required
def relatorio(request):
    visitas = visita.objects.all()

    #SE CLICAR EM DELETAR VISITA
    busca = request.GET.get('delete')
    if busca:
        print(busca)
        deletar = visita.objects.get(id=busca)
        print(deletar)
        deletar.delete()

    #aparecer o indice de quantas visitas em #
    indice = 1
    for item in visitas:
        item.indice = indice
        indice = indice+1
    return render(request, 'core/relatorio.html', {"visitas":visitas, "nome_pagina":"Visitas e Demandas"})

@login_required
def contatos(request):
    pessoas = visitante.objects.all()

     #SE CLICAR EM DELETAR VISITA
    busca = request.GET.get('delete')
    if busca:
        print(busca)
        deletar = visitante.objects.get(id=busca)
        print(deletar)
        deletar.delete()

    #aparecer o indice de quantas visitas em #
    indice = 1
    for item in pessoas:
        item.indice = indice
        indice = indice+1

    return render(request, 'core/visitantes.html', {"pessoas":pessoas, "nome_pagina":"Visitantes"})

core/templates/base/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Controle de Visita</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    <style>
      .fundo{
        background-color: rgba(10,23,55,0.7);
        padding: 15px;
        color: white;
    }
    .esquerda{
      text-align: right;
    }
    </style>

    <div class="container">
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'home' %}" class="nav-link" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="{% url 'cadastro' %}" class="nav-link">Cadastrar</a></li>
            <li class="nav-item"><a href="{% url 'relatorio' %}" class="nav-link">Visitas</a></li>
            <li class="nav-item"><a href="{% url 'contatos' %}" class="nav-link">Visitantes</a></li>
            {% if request.user.is_authenticated %}
              <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link" style="color: #F70505">Sair</a></li>
            {% endif %}
        </ul>

                
        <div class="col-md-12 fundo">
            <div class="col-md-5">
              <label>{{nome_pagina}}</label>
            </div>
            <div class="col-md-6 esquerda" >
              <!--<button type="button " class="btn btn-danger btn-sm">DELETAR</button> -->
            </div>
        </div>
        <br>
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/cadastro.html
{% extends "base/base.html" %}

{% block content %}

<div class="form-control">
  <div align="center">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalvisitante">
    Buscar Visitante
  </button>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="modalvisitante" tabindex="-1" aria-labelledby="modalvisitanteLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalvisitanteLabel">Buscar Visitante Cadastrado</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <form method="get" id="search-form" class="form-inline">

        <div class="modal-body">
            <label for="pessoa" class="form-label">Nome</label>
            <select name="search" class="form-select">
              {% for visitante in visitantes %}
              <option value ="{{visitante.id}}" >{{visitante.nome}} - {{visitante.cidade}}/{{visitante.estado}}  </option>  <!--  - {{visitante.cidade}}/{{visitante.estado}}</option> --> 
              {% endfor %}
            </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" id="search"  class="btn btn-primary">Carregar Dados</button>
        </div>

        </form>
      </div>
    </div>
  </div>


  <form class="row g-3" method="post">

    {% csrf_token %}
    <div class="col-md-12">
      <h6>{{horas}}</h6>
      <label for="id_visitante" class="form-label">Código:</label>
      <input type="text" id="id_visitante" name="id_visitante" value="{{atualizando.id}}" disabled="">
    </div>

    <div class="col-md-6">
      <label for="name" class="form-label">Nome Completo</label>
      <input type="text" name="name" class="form-control" placeholder="Nome Completo" aria-label="Nome Completo" value="{{atualizando.nome}}">
    </div>

    <div class="col-md-6">
      <label for="mail" class="form-label">E-mail</label>
      <input type="email" name="mail" class="form-control"  placeholder="e-mail" aria-label="e-mail" value="{{atualizando.email}}">
    </div>

    <div class="col-md-6">
      <label for="cel" class="form-label">Celular</label>
      <input type="text" name="cel" class="form-control" placeholder="Celular" aria-label="Celular" value="{{atualizando.celular}}">
    </div>
    
    <div class="col-md-6">
      <label for="fone" class="form-label">Telefone</label>
      <input type="text" name="fone" class="form-control" placeholder="Telefone" aria-label="Telefone" value="{{atualizando.fone}}">
    </div>

    <div class="col-md-2">
      <label for="zip" class="form-label">CEP</label>
      <input type="text" name="zip" class="form-control" value="{{atualizando.cep}}">
    </div>

    <div class="col-md-10">
      <label for="address" class="form-label">Endereço</label>
      <input type="text" name="address" class="form-control"  placeholder="Quadra xxx , Alameda xx , 00" value="{{atualizando.endereco}}">
    </div>

    <div class="col-md-5">
      <label for="complement" class="form-label">Complemento</label>
      <input type="text" name="complement" class="form-control" placeholder="Apto, Condominio, Qi." value="{{atualizando.complemento}}">
    </div>

    <div class="col-md-4">
      <label for="city" class="form-label">Cidade</label>
      <input type="text" name="city" class="form-control" value="{{atualizando.cidade}}" >
    </div>

    <div class="col-md-3">
      <label for="state" class="form-label">Estado</label>
      <select name="state" class="form-select">
        <option selected> ... </option>
        <option>DF</option>
        <option>TO</option>
      </select>
    </div>

    <div class="col-mb-3">
      <label for="description" class="form-label">Descrição da Visita</label>
      <textarea type="text" name="description" class="form-control" rows="3"></textarea>
    </div>

    <div class="col-12" align="center">
      <button type="submit" class="btn btn-primary">CADASTRAR VISITA</button>
    </div>

  </form>

</div>

{% endblock %}

core/templates/core/home.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Controle de Visita</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    <style>
      .fundo{
        background-color: rgba(10,23,55,0.7);
        padding: 20px;
        margin: 200px auto;
        text-align: center;
        color: white;        
      }
    .esquerda{
      text-align: right;
    }
    </style>

    <div class="container">
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'home' %}" class="nav-link" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="{% url 'cadastro' %}" class="nav-link">Cadastrar</a></li>
            <li class="nav-item"><a href="{% url 'relatorio' %}" class="nav-link">Visitas</a></li>
            <li class="nav-item"><a href="{% url 'contatos' %}" class="nav-link">Visitantes</a></li>
            {% if request.user.is_authenticated %}
              <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link" style="color: #F70505">Sair</a></li>
            {% endif %}
        </ul>

<div class="row">
    <div class="col-md-12 fundo">
      <h2> SISTEMA PARA CADASTRO DE VISITAS - BASIC_APPS SDP </h2>
      <a href="https://api.whatsapp.com/send?phone=5563981269417" style="color: #FFFFFF" target="_blank" >Clique aqui para acionar Suporte</a>
    </div>
  
  </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/relatorio.html
{% extends "base/base.html" %}

{% block content %}
<div class="form-control">
    
  <div class="row">
    <div class="col-md-6">
      <form method="get" id="search-form" class="form-inline">
        <div class="input-group mb-3">
          <input type="search"  name="search" class="form-control mr-sm-2" placeholder="Pesquisar" aria-label="Buscar Visita" aria-describedby="Pesquisar Visita">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" id="buscar">Pesquisar</button>
        </div>
      </form>
    </div>
  </div>    


  <table class="table table-striped">
    <thead>
      <tr>
        <!--<th scope="col">#</th>-->
        <th scope="col">#</th>
        <th scope="col">Data</th>
        <th scope="col">Nome</th>
        <th scope="col">Telefones</th>
        <th scope="col">Cidade</th>
        <th scope="col">Descrição</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>
      {% for item in visitas %}
      <tr>
        <!--<td>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
          </div> 
        </td>-->
        <td scope="row">{{item.indice}}</td>
        <td>{{item.data}} </td>
        <th>{{item.visitante.nome}} </th>
        <td>{{item.visitante.fone}} // {{item.visitante.celular}}  </td>
        <td>{{item.visitante.cidade}} // {{item.visitante.estado}} </td>
        <td>{{item.descricao}}</td>
        <td>
            <a type="button" id="delete" href="?delete={{item.id}}"  class="btn btn-danger btn-sm">DELETAR</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>  

{% endblock %}

core/templates/core/visitantes.html
{% extends "base/base.html" %}

{% block content %}
<div class="form-control">
  <div class="row">
    <div class="col-md-6">
      <form method="get" id="search-form" class="form-inline">
        <div class="input-group mb-3">
          <input type="search"  name="search" class="form-control mr-sm-2" placeholder="Pesquisar" aria-label="Buscar Visita" aria-describedby="Pesquisar Visita">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" id="buscar">Pesquisar</button>
        </div>
      </form>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Data</th>
        <th scope="col">Nome</th>
        <th scope="col">Telefones</th>
        <th scope="col">E-mail</th>
        <th scope="col">Cidade</th>
      </tr>
    </thead>
    <tbody>
      {% for item in pessoas %}
      <tr>
        <td>{{item.indice}}</td>
        <td>{{item.data}} </td>
        <th scope="row">{{item.nome}} </th>
        <td>{{item.fone}} // {{item.celular}}  </td>
        <td>{{item.email}} </td>
        <td>{{item.cidade}} // {{item.estado}} </td>
        <td>
          <a type="button" id="delete" href="?delete={{item.id}}"  class="btn btn-danger btn-sm">DELETAR</a>
      </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}